### ISSUE TITLE
[Request] New version

### ISSUE THREAD

**Issue by cottinisimone** [stalwartlabs/mail-builder#1]
Hello @mdecimus.

First of all thank you for your work on this library. 

I was trying to use this lib at the `0.1.2` version but i found too the bug you fixed [here](https://github.com/stalwartlabs/mail-builder/commit/6af21303e624591f70fe1317f8b80ea6c8e0bcc7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R302). Do you think that a new version of this lib could be available soon?

Thank you in advance.

**Comment by mdecimus** [comment]
Hi @cottinisimone,

Sure! I'll release the a new version tomorrow. I'll let you know as soon as it's published.

Cheers

**Comment by mdecimus** [comment]
@cottinisimone - Done, version 0.1.3 is out!

**Comment by cottinisimone** [comment]
Thank you so much!
