### ISSUE TITLE
Addition of BodyPart::Raw

### ISSUE THREAD

**Issue by mdsimmo** [stalwartlabs/mail-builder#17]
I'd like to be able to write a custom encoding type, as allowed for by [RFC 2045 p.15](https://www.ietf.org/rfc/rfc2045.txt).

This body type would operate exactly like `BodyType::Text/Binary`, but not add any `Content-Transfer-Encoding` headers, and directly write a raw `[u8]` to the output.

**Comment by mdecimus** [comment]
You can add use a Binary part and add the headers you need manually. No changes are needed in the code to support this.

**Comment by mdecimus** [comment]
This is now possible on version 0.3.1, available on the repo.
