### ISSUE TITLE
Sending email - how?

### ISSUE THREAD

**Issue by nicraMarcin** [stalwartlabs/mail-builder#2]
Hi, 
could you give example of what smtp client is the best for your lib to sending email?

**Comment by mdecimus** [comment]
Hi,
I plan to add SMTP sending support in a few weeks but in the meantime you could try using this library:
https://crates.io/crates/letterman

**Comment by nicraMarcin** [comment]
Nice, so I will be waiting 👍

**Comment by mdecimus** [comment]
Hi @nicraMarcin 
Well, it took a few months but the support for sending emails is finally here:

https://github.com/stalwartlabs/mail-send

Use mail-send instead which includes also mail-builder.
