### ISSUE TITLE
Custom Content-Transfer-Encoding leads to duplicated header

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-builder#21]
Let's say I have a `MimePart`. If I do sth like:

```rust
part.header("Content-Transfer-Encoding", Raw::new("8bit"));
```

then the final generated MIME message contains twice the `Content-Transfer-Encoding` header. What could be the best way to solve this matter?

**Comment by mdecimus** [comment]
Support for custom `Content-Transfer-Encoding` was added to version `0.3.1`, you should be able to specify a custom CTE as in your example or using the `transfer_encoding` method.
However, I just realized that I never published this version to crates. Can you confirm that the version in the repository allows you to do this? If so I'll publish it.

**Comment by soywod** [comment]
> Can you confirm that the version in the repository allows you to do
> this? If so I'll publish it.

I confirm that it works as expected on `master`, thank you. Let me know
when you publish the new version!

**Comment by mdecimus** [comment]
Done, `v0.3.1` has been published.

**Comment by soywod** [comment]
Looks like there is an issue with `mail-send`. Somehow I cannot have both `mail-builder` and `mail-send` together, it cannot take the `v0.3.1` as a common version.

**Comment by mdecimus** [comment]
Are you using mail-send `0.4`?

**Comment by soywod** [comment]
> Are you using mail-send `0.4`?

In fact mail-parser was not up-to-date (v0.8). I bumped it to v0.9 (and
took time to fix breaking changes) and it seems to work as expected
now. I like the idea of `MessageParser` and the way `Address` variants
are design! Thank you for the great work.

**Comment by mdecimus** [comment]
Great! Make sure you are on mail-parser `0.9.1` as it fixes a panic when the `content_disposition` function was called on invalid Content-Disposition headers.
