### ISSUE TITLE
Invalid adresses

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-builder#28]
`MessageBuilder::new().to("test <test@localhost>")` generates the following message:

```eml
To: <test <test@localhost>>
Message-ID: <180a04f3720c7c68.6917150f5ed0b62d.999d2c86623c9fb9@soywod>
Date: Thu, 21 Nov 2024 15:20:50 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
```

Instead of `To: test <test@localhost>`.

**Comment by mdecimus** [comment]
Mail builder does not support parsing the name and address components or a recipient or a sender. You need to specify them separately such as `.to(("test", "test@localhost"))`
