### ISSUE TITLE
Cut down on rand dependency

### ISSUE THREAD

**Issue by alexwennerberg** [stalwartlabs/mail-builder#3]
Unless I am mistaken or don't understand the RFCs, message boundaries don't need high quality RNG. I believe you can replace with https://git.alexwennerberg.com/misc/file/rand.rs.html or a simpler non-cryptographic rng library

**Comment by mdecimus** [comment]
Thanks, I'll give it a try.

**Comment by mdecimus** [comment]
Just committed this fix. Ended up using a thread local counter combined with fibonacci hashing.

**Comment by alexwennerberg** [comment]
whats the reason for gethostname? could that part be dropped as well?

**Comment by mdecimus** [comment]
It's used to generate slightly more unique message IDs. However this could be moved as an optional dependency as the chances that two machines generate the same message Id at the same time are quite low.
